### PR TITLE
[Scribe Note] Add Jan 17 Lecture Scribe Note

### PR DESCRIPTION
**Pull request by atulyakumar97**
Scribe note: Jan 17 Lecture

Credit: @aryarahnama @atulyakumar97

### CODE REVIEW

**Comment by SumanthRH** [comment]
Hi,

Thanks for the submission! I realise this might be the first time scribing for some of you, so I want to clarify what we expect from a scribe (cross-posting from Piazza):

> The scribe should faithfully capture the professor’s explanations in the lecture. We expect the notes to have the same structure/main sections as the slides, and many similar wordings as well. Additionally, the notes should also have helpful examples given by the professor in the class, additional context for different topics when needed, etc. The TAs will assess your notes based on the contents in the slides.
> 
> You should not, however, try to rearrange the content as you see fit, or add in material from the additional readings provided. The scribe notes do not have to be a self-contained document on the topic - we’re only looking for you to capture what was taught in class.
> 

Some specific feedback for your case: You've added the Locality topic (a Comp Arch topic) under OS Memory Management. I also see that you've included a lot of content from the additional readings provided. This is great if you're building a self contained document on OS basics, but not what we want from a scribe. I also see that some smaller sections have been rearranged and do not reflect the lecture. I hope you can modify your notes based on this.

**Review by SumanthRH — CHANGES_REQUESTED** [review]
Hi,

Thanks for the submission! I realise this might be the first time scribing for some of you, so I want to clarify what we expect from a scribe (cross-posting from Piazza):

> The scribe should faithfully capture the professor’s explanations in the lecture. We expect the notes to have the same structure/main sections as the slides, and many similar wordings as well. Additionally, the notes should also have helpful examples given by the professor in the class, additional context for different topics when needed, etc. The TAs will assess your notes based on the contents in the slides.
> 
> You should not, however, try to rearrange the content as you see fit, or add in material from the additional readings provided. The scribe notes do not have to be a self-contained document on the topic - we’re only looking for you to capture what was taught in class.
> 

Some specific feedback for your case: You've added the Locality topic (a Comp Arch topic) under OS Memory Management. I also see that you've included a lot of content from the additional readings provided. This is great if you're building a self contained document on OS basics, but not what we want from a scribe. I also see that some smaller sections have been rearranged and do not reflect the lecture. I hope you can modify your notes based on this.

**Comment by atulyakumar97** [comment]
@SumanthRH - Could you please do a re-review? Made the changes as per your review comments.

**Review by SumanthRH — APPROVED** [review]
Great! Thanks for working on this!

**Pull request merged**
