### PR TITLE
Create Mar_1_scribe_note.pdf

### PR DESCRIPTION
**Pull request by Yunzhou123**
Create march_1_scrive_note.pdf from Yunzhou

### CODE REVIEW

**Comment by SumanthRH** [comment]
I see that Adhvaith Vijay is also mentioned as a scribe for this lecture on the sign-up sheet. Was this prepared solely by you @Yunzhou123 (that's what the pdf says)? Also, please fix the title in the pdf to "Streaming Processing - 2"

**Comment by Yunzhou123** [comment]
Dear Sumanth,

I  am so sorry that I didn’t know that Adhvaith also signed up for this scribe because I only check that there are no scriber 2. Yes, for this version, it is solely done by me. I will update the title as soon as possible and will be happy to make more modifications. Thank you.

With best regards,

Yunzhou

发自我的iPhone

**Review by SumanthRH — CHANGES_REQUESTED** [review]
@Yunzhou123 please coordinate with Adhvaith and submit one PDF which combines both of your contributions.

**Comment by Yunzhou123** [comment]
Dear Sumanth,

I  think that Adhvaith may have dropped the class because I cannot find his
name on Canvas. Thank you so much for your time and consideration.

With best regards,

Yunzhou

**Review by SumanthRH — CHANGES_REQUESTED** [review]
@Yunzhou123  Please change the title of the pdf to "Stream Processing - 2". Content looks good!

**Comment by Yunzhou123** [comment]
Hi SumanthRH. I have just changed the title. Thank you!

**Review by SumanthRH — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
